### ISSUE TITLE
Halp I am trapped in a test issue

### ISSUE THREAD

**Issue by notwaldorf** [cdata/polyrelease#1]
Can anybody hear me?

Hello?

**Comment by cdata** [comment]
This issue appears to be fixed in master. Please re-open the issue if you think there is still a problem!

**Comment by notwaldorf** [comment]
[![selfie-0](http://i.imgur.com/0keBUmW.png)](https://github.com/thieman/github-selfies/)

**Comment by notwaldorf** [comment]
[![selfie-1](http://i.imgur.com/BmJ3nAD.gif)](https://github.com/thieman/github-selfies/)

**Comment by notwaldorf** [comment]
MUCH PROBLEM STILL TRAPPED
